# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: ^messages.*
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-jsonschema
        files: ^messages.*
        args: ["--schemafile", ".vscode/messages.schema.json"]
  - repo: https://github.com/awslabs/git-secrets
    rev: 5357e18bc27b42a827b6780564ea873a72ca1f01
    hooks:
      - id: git-secrets
        entry: git-secrets
        args: ["--register-aws", "--pre_commit_hook"]
