# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        files: ^messages.*
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-json
  - repo: https://github.com/psf/black
    hooks:
      - id: black
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.1
    hooks:
      - id: check-jsonschema
        files: ^messages.*
        args: ["--schemafile", ".vscode/messages.schema.json"]
